[package]
name = "wasm_websocket_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]


[dependencies]
reqwest = "0.11.14"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.34"
